include: package:solid_lints/analysis_options.yaml

linter:
  rules:
     public_member_api_docs: false

dart_code_metrics:
  rules:
    - prefer-match-file-name:
        exclude:
          - lib/main.dart